name: release

on:
  push:
    branches:
      - deploy
    tags-ignore:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PYTHON_ENV: ci
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.QMBOT_GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: run postgres
        run: make postgresql
      - name: Install dependencies
        run: make install
      - name: test version
        run: make test-version
      - name: lint
        run: make test-lint
      - name: run tests
        run: make test
      - name: build python bundle
        run: make bundle
      - name: release to pypi
        run: make release-pypi
      - name: release to github
        run: make release-github
